
title: "BROWSER2021 CODE"
author: "Laurens Inauen"
email: "laurens.hwm@gmail.com"
description: Computational Thinking in Composition.
theme: minima
skin: dark
header_pages:
  - index.md
  - example1.md
plugins:
 - jekyll-feed
 - jekyll-seo-tag
github_username: laurens-in
instagram_username: iiaurens